
Ttree:
  Yubico:
    api:
      clientId: '[replace by your own]'
      secrectKey: '[replace by your own]'
Neos:
  Flow:
    object:
      excludeClasses:
        enygma.yubikey:
          - 'Yubikey\\.*'
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            provider: \Ttree\Yubico\Authentication\Provider\PersistedUsernamePasswordProvider
            tokenClass: \Ttree\Yubico\Authentication\Token\UsernamePassword
