TYPO3:

  Flow:

    object:
      excludeClasses:
       'enygma.yubikey': ['Yubikey\\.*']

    security:
      authentication:
        providers:
          Typo3BackendProvider:
            provider: '\Ttree\Yubico\Authentication\Provider\PersistedUsernamePasswordProvider'
            tokenClass: '\Ttree\Yubico\Authentication\Token\UsernamePassword'

Ttree:

  Yubico:

    api:
      clientId: '20607'
      secrectKey: 'JX/hzPIhNyptfeKNmV+TR/xzyMY='